config/routes.rb
Rails.application.routes.draw do
#   resources :gallery
    get 'gallery/new'
    get 'gallery', controller: 'gallery', action: 'index'
    post 'gallery', controller: 'gallery', action: 'create'
    get 'gallery/manage/:id', controller: 'gallery', action: 'manage'
    put "gallery/add_to_gallery/:id", controller: 'gallery', action: 'add_to_gallery'
    put "gallery/remove_from_gallery/:id", controller: 'gallery', action: 'remove_from_gallery'
    put "gallery/remove/:id", controller: 'gallery', action: 'remove_gallery'
    put "gallery/upload", controller: 'gallery', action: 'upload_to_gallery'
#   root to: 'gallery#index'
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    model_name.instance_variable_set(:@route_key, 'gallery')
    has_many :gallery_images, :dependent => :destroy
end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
    belongs_to :gallery
    has_one_attached :image
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  before_action :set_gallery, only: [:show, :manage, :update, :destroy]

  def index
    @page = 'gallery'
    @galleries = Gallery.all
  end

  def manage
    @page = 'manage'
    if params[:id]
        @gallery = Gallery.find(params[:id])
    else
        redirect_to gallery_path and return
    end

  end

  def add_to_gallery
    if !params[:id]
        redirect_back(fallback_location: admin_gallery_path) and return
    end

    ap "adding pfiSet: #{params[:id]} to gallery images"

    gallery = Gallery.first
    ### get pfiSet and copy to giSet
    pfiSet = PortfolioImage.find(params[:id])
    giSet = GalleryImage.where(gallery_id: gallery.id, portfolio_images_id: pfiSet.id).first_or_create
    giSet.before.attach(io: StringIO.new(pfiSet.before.download), filename: pfiSet.before.filename, content_type: pfiSet.before.content_type)
    giSet.after.attach(io: StringIO.new(pfiSet.after.download), filename: pfiSet.after.filename, content_type: pfiSet.after.content_type)
    giSet.caption = pfiSet.portfolio.user.first_name + " " + pfiSet.portfolio.user.last_name + " | " + pfiSet.portfolio.user.city + ", " + pfiSet.portfolio.user.state
    giSet.portfolio_images_id = pfiSet.id
    giSet.save

  end

  def upload_to_gallery
    ### do we have uploaded portfolio images
    if params[:image] && params[:gallery_id]
        image = params[:image]
        caption = params[:caption]
        gallery = Gallery.find(params[:gallery_id])
        gImage = GalleryImage.new
        gImage.gallery_id = gallery.id

        gImage.image.attach(io: File.open(image.path), filename: image.original_filename, content_type: image.content_type)
        gImage.caption = (caption.blank?)? " " : caption
        gImage.save
    
        flash[:success] = "Image was successfully added to the gallery"
        redirect_back(fallback_location: gallery_path) and return
    else
        flash[:error] = "Something went wrong... what did you do?!"
        redirect_back(fallback_location: gallery_path) and return

    end



  end

  def remove_gallery
    if !params[:id]
        redirect_to gallery_path and return
    end

    gallery = Gallery.find(params[:id])
    gallery.destroy
  end

  def remove_from_gallery
    if !params[:id]
        redirect_back(fallback_location: gallery_path) and return
    end

    rmImage = GalleryImage.find(params[:id])
    rmImage.destroy
  end

  def show

  end

  # GET /gallery/new
  def new
    @gallery = Gallery.new
  end

  # POST /gallery
  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to @gallery, notice: 'Gallery was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gallery/1
  def update
    if @gallery.update(gallery_params)
      redirect_to @gallery, notice: 'Gallery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gallery/1
  def destroy
    @gallery.destroy
    redirect_to gallery_url, notice: 'Gallery was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
    #   params.fetch(:gallery, :title, {})
      params.require(:gallery).permit(:title)
    end

end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/_carousel.html.erb
<!-- Start Embeded Gallery Area -->
<%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "dgw_gallery/dgw_gallery_style.css" %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<% if !@gallery.gallery_images.blank? %>
    <div id="dgwGalleryIndicators" class="carousel slide" data-bs-ride="carousel" data-bs-interval="5000">
        <div class="carousel-inner">
            <% @gallery.gallery_images.each_with_index do |gi, idx| %>
                <div  data-bs-interval="5000" class="carousel-item <%= (idx == 0)? "active" : nil %>">
                    <figure>
                        <%= image_tag gi.image.variant(resize_to_fill: [900, 500]), class: "img-fluid border-radius-xl" %>
                    </figure>
                    <figcaption class="blockquote-footer text-center">
                        <%= gi.caption %>
                    </figcaption>
                </div>
            <% end %>
        </div>
    </div>
<% else %>
    <div class="col-12 text-center">
        There Are No Slides to Display. Please add some.
    </div>
<% end %>
<!-- End Embeded Gallery Area -->

app/views/gallery/_form.html.erb
<%= form_for @gallery do |form| %>
    <% if gallery.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>
            <ul>
                <% gallery.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <section class="py-3 justify-content-center text-center">
        <div class="container">
            <div class="row justify-space-between py-2">
                <div class="col-lg-4 mx-auto">
                    <div class="input-group input-group-static mb-4">
                        <label>Gallery Name</label>
                        <%= form.text_field :title, class: 'form-control' %>
                    </div>
                </div>
            </div>
        </div>
        <div class="actions ">
            <%= form.submit 'Create Gallery', class: 'btn btn-primary border-radius-md' %>
        </div>
    </section>
<% end %>

app/views/gallery/add.html.erb
<div class="card card-body border-radius-xl blur shadow-blur mx-3 mx-md-4 mt-n5 overflow-visible">
    <!-- -------- START Features w/ image on left & title & text & 3 cols on soft background -------- -->
    <section class="py-3 d-sm-block d-block d-md-block">
        <div class="container">
            <div class="row mb-4 mt-n5">
                <div class="card card-body border-radius-xl col-12">
                    <div class="row text-center justify-content-center">
                        <div class="col-12 col-md-12">
                            <div class="btn-group" role="toolbar" aria-label="Basic example">
                                <div class="btn-group" role="toolbar" aria-label="Basic example">
                                    <%= link_to gallery_index_path, class: "text-decoration-none #{(@page == 'gallery')? 'text-danger' : 'text-navy'} mx-1 mx-md-5 position-relative overflow-visible", data: {"bs-container" => "body", "bs-toggle" => "popover", "bs-trigger" => "click hover focus", html: true, sanitize: false, "bs-placement" => "top", "bs-title" => "Pending Approval", "bs-content" => "Main profile images pending approval"} do%>
                                        <i class="far fa-chalkboard-teacher fs-1" ></i>
                                        <p class="small">Manage Gallery</p>
                                    <% end %>
                                    <%= link_to gallery_add_path, class: "text-decoration-none #{(@page == 'add')? 'text-danger' : 'text-navy'} mx-1 mx-md-5 position-relative overflow-visible", data: {"bs-container" => "body", "bs-toggle" => "popover", "bs-trigger" => "hover focus", "bs-placement" => "top", "bs-title" => "Pending Approval", "bs-content" => "Porfolio / Work Example images pending approval"} do%>
                                        <i class="far fa-images fs-1" ></i>
                                        <p class="small">Add to Gallery</p>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="card card-body border-radius-xl col-12">
                    <div class="row text-center justify-content-center">
                        <h4>Add Image to Gallery</h4>
                    </div>
                    <div class="row text-center mt-1 d-flex align-items-stretch">
                        <div class="col-12 col-md-8 mx-auto">
                            <div class="mt-2 border-radius-xl mb-0">
                                <div class="card-header mt-3 mx-auto border-radius-xl p-2 bg-transparent position-relative z-index-2  blur-shadow-image dark-shadow ">
                                    <%= form_tag gallery_upload_path, id: "gallery_upload_form", name: "gallery_upload_form", method:"PUT", multipart: true do %>
                                        <div class="row">
                                            <div class="col-6">
                                                <figure>
                                                    <%= image_tag "no_image.png", class: "img-fluid border-radius-xl mt-3", width: "300px", height: "300px", id: "g_image" %>
                                                    <figcaption>Gallery Image</figcaption>
                                                    <div class="text-center mt-3 text-black">
                                                        <span class="btn-file">
                                                            <%= file_field_tag "image", id: "image" %>
                                                            <label for="image">
                                                                <i class="fs-4 fa fa-camera-retro"></i> Upload After Image
                                                            </label>
                                                        </span>
                                                    </div>
                                                </figure>
                                            </div>
                                        </div>
                                        <div class="row mx-auto justify-content-center">
                                            <%= text_field_tag "caption", nil, class: "form-control w-50 text-center", placeholder: "Enter caption for image", required: false %><br>
                                            <p>
                                                <button type="submit" class="w-auto mt-2 btn btn-sm btn-primary">Add to Gallery</button>
                                            </p>
                                        </div>
                                    <% end %>
                                </div>
                                <div class="card-body text-center">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script>
    $(document).ready(function() {

        function readURL(input, targetTag) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(targetTag).attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }


        $("#image").change(function(){
            readURL(this, "#g_image");
        });
    });
</script>

app/views/gallery/index.html.erb
<%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "dgw_gallery/dgw_gallery_style.css" %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<div class="container mt-3">
    <div class="row mb-4">
        <div class="card card-body bg-gradient-gallery border-radius-xl shadow-lg border-top-0 col-12">
            <div class="row justify-content-center">
                <div class="col-6 justify-content-center d-flex align-items-center">
                    <div class="col-2 d-flex align-items-center">
                        <%= image_tag "dgw_logo.png", class: 'align-items-center', height: "100px" %>
                    </div>
                    <div class="col-8 d-flex align-items-center h-100">
                        <h2 class="text-active">DevGW Gallery <span class="fs-5">(v <%= DgwGallery::VERSION %>)</span></h2>
                    </div>
                </div>
            </div>
            <div class="row text-center justify-content-center">
                <div class="col-12">
                    <div class="btn-group mt-2 mb-3" role="toolbar" aria-label="Basic example">
                        <span class="text-active">Gallery Home</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-5">
        <div class="card card-body shadow-lg border-1 border-radius-xl col-12">
            <div class="row">
                <% if @galleries.count > 0 %>
                    <div class="row justify-space-between py-2 text-center">
                        <h4 class="text-center">Existing Galleries</h4>
                        <hr class="">
                        <%= link_to gallery_new_path, class: 'text-end text-primary' do %>
                            <span class="mb-5 text-end"><i class="fa fa-plus"></i> New Gallery</span>
                        <% end %>
                        <% @galleries.each do |gallery| %>
                            <div class="col-12 col-md-3 mt-3 mx-auto mb-5 move-on-hover d-flex align-items-stretch" id="<%= gallery.id.to_s %>">
                                <div class="card border-1 shadow-lg mt-3 border-radius-xl">
                                    <div class="card-header mt-4 mx-3 p-0 bg-transparent position-relative z-index-2">
                                        <span class="text-black text-sm">Gallery ID: <%= gallery.id.to_s %></span>
                                        <span class="d-block blur-shadow-image">
                                            <%= image_tag ((!gallery.gallery_images.blank? && gallery.gallery_images.first.image.attached?)? gallery.gallery_images.first.image.variant(resize_to_fill: [300, 300]) : "no_gallery_images.png"), class: "mt-2 img-fluid border-radius-xl" %>
                                        </span>
                                    </div>
                                    <div class="card-body p-1 text-center">
                                        <div class="row">
                                            <div class="col-12">
                                                <p class="text-black"><%= gallery.title %></p>
                                            </div>
                                            <div class="col-12 text-center">
                                                <%= button_tag "Remove", class: 'btn btn-danger btn-sm', onclick: "removeGallery(#{gallery.id})", data: {confirm: "Are you sure?\n\nThis will permanently remove the gallery and all attached images."} %>
                                                <%= link_to "/gallery/manage/#{gallery.id}", class: "text-decoration-none" do %>
                                                    <%= button_tag "Manage", class: 'btn btn-info btn-sm' %>
                                                <% end %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                <% else %>
                    <div class="col-12 text-center">
                        <h3>You currently have no galleries</h3>
                        <%= link_to gallery_new_path do %>
                            <%= button_tag "Create a Gallery", class: 'btn btn-info border-radius-lg mt-2' %>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<script>
    function removeGallery(id){
            $.ajax({
                type: 'put',
                url: '/gallery/remove/' + id,
                success: function(){
                    $("#"+id).hide('slow', function(){ $target.remove(); });
                }
            });

    }
</script>

app/views/gallery/manage.html.erb
<%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "dgw_gallery/dgw_gallery_style.css" %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<div class="container mt-3">
    <div class="row mb-4">
        <div class="card card-body bg-gradient-gallery border-radius-xl shadow-lg border-top-0 col-12 shadow-lg">
            <div class="row justify-content-center">
                <div class="col-6 justify-content-center d-flex align-items-center">
                    <div class="col-2 d-flex align-items-center">
                        <%= image_tag "dgw_logo.png", class: 'align-items-center', height: "100px" %>
                    </div>
                    <div class="col-8 d-flex align-items-center h-100">
                        <h2 class="text-active">DevGW Gallery <span class="fs-5">(v <%= DgwGallery::VERSION %>)</span></h2>
                    </div>
                </div>
            </div>
            <div class="row text-center justify-content-center">
                <div class="col-12">
                    <div class="btn-group" role="toolbar" aria-label="Basic example">
                        <%= link_to gallery_path do %>
                            <%= button_tag "Back to Gallery Home", type: 'button', class: 'btn btn-primary btn-small' %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="card card-body border-radius-xl col-12 text-black shadow-lg" id="galleryCodeSection">
            <div class="row">
                <h4 class="text-center">Gallery Preview</h4>
            </div>
            <div class="row justify-content-center align-items-evenly">
                <div class="col-5 bg-light rounded mx-5 h-100">
                    <div class="card-header mt-3 border-radius-xl bg-transparent position-relative z-index-2  blur-shadow-image dark-shadow">
                        <%= render 'gallery/carousel' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="card card-body border-1 shadow-xl border-radius-xl col-12 shadow-lg">
            <div class="row text-center justify-content-center">
                <h4>Add Image to Gallery</h4>
            </div>
            <div class="row text-center mt-1 d-flex align-items-stretch">
                <div class="col-12 mx-auto">
                    <div class="card-header mt-1 mx-auto border-radius-xl p-2 bg-transparent position-relative z-index-2  blur-shadow-image dark-shadow ">
                        <%= form_tag gallery_upload_path, id: "gallery_upload_form", name: "gallery_upload_form", method:"PUT", multipart: true do %>
                            <%= hidden_field_tag "gallery_id", @gallery.id %>
                            <div class="row justify-content-center align-items-center">
                                <div class="col-2">
                                    <figure>
                                        <%= image_tag "no_image_selected.png", class: "img-fluid border-radius-xl mt-1", width: "150px", height: "150px", id: "g_image" %>
                                        <figcaption>
                                            <div class="text-center mt-1 text-black">
                                                <span class="btn-file">
                                                    <%= file_field_tag "image", id: "image" %>
                                                    <label for="image">
                                                        <i class="fs-4 fa fa-camera-retro"></i>
                                                        <p>upload</p>
                                                    </label>
                                                </span>
                                            </div>
                                        </figcaption>
                                    </figure>
                                </div>
                                <div class="col-2">
                                    <div class="form-group input-group-static p-0">
                                        <label class="mb-2">Image Caption</label>
                                        <%= text_field_tag "caption", nil, class: "form-control", required: false %><br>
                                    </div>
                                    <p>
                                        <button type="submit" class="w-auto mt-2 btn btn-sm btn-primary">Add to Gallery</button>
                                    </p>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="card card-body border-1 shadow-xl border-radius-xl col-12 shadow-lg">
            <% if @gallery.gallery_images.count > 0 %>
                <div class="row justify-space-between py-2 text-center">
                    <h4 class="text-center">Images in gallery: <%= @gallery.title %></h4>
                    <hr class="">
                    <% @gallery.gallery_images.each do |gImage| %>
                        <div class="col-12 col-md-3 mx-auto mb-5 move-on-hover d-flex align-items-stretch" id="<%= gImage.id %>">
                            <div class="card border-1 shadow-lg mt-3 border-radius-xl">
                                <div class="card-header mt-4 mx-3 p-0 bg-transparent position-relative z-index-2">
                                    <span class="d-block blur-shadow-image">
                                        <%= image_tag gImage.image.variant(resize_to_fill: [500, 350]), class: "img-fluid border-radius-xl" %>
                                    </span>
                                </div>
                                <div class="card-body p-1 text-center">
                                    <div class="row">
                                        <div class="text-black inline-block"><%= gImage.caption %></div>
                                        <div class="col-12 text-center">
                                            <%= button_tag "Remove Image", class: 'btn btn-danger btn-sm', onclick: "removeFromGallery(#{gImage.id})", data: {confirm: "Are you sure?\n\nThis will permanently remove the image."} %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% else %>
                <div class="col-12 text-center">
                    <h3>You currently have no gallery images</h3>
                </div>
            <% end %>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {

        function readURL(input, targetTag) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(targetTag).attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }


        $("#image").change(function(){
            readURL(this, "#g_image");
        });
    });
</script>
<script>
    function removeFromGallery(id){
            $.ajax({
                type: 'PUT',
                url: '/gallery/remove_from_gallery/' + id,
                success: function(){
                    $("#"+id).hide('slow', function(){ $target.remove(); });
                }
            });

    }
</script>

app/views/gallery/new.html.erb
<%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "dgw_gallery/dgw_gallery_style.css" %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<div class="container mt-3">
    <div class="row mb-4">
        <div class="card card-body bg-gradient-gallery border-radius-xl shadow-lg border-top-0 col-12">
            <div class="row justify-content-center">
                <div class="col-6 justify-content-center d-flex align-items-center">
                    <div class="col-2 d-flex align-items-center">
                        <%= image_tag "dgw_logo.png", class: 'align-items-center', height: "100px" %>
                    </div>
                    <div class="col-8 d-flex align-items-center h-100">
                        <h2 class="text-active">DevGW Gallery <span class="fs-5">(v <%= DgwGallery::VERSION %>)</span></h2>
                    </div>
                </div>
            </div>
            <div class="row text-center justify-content-center">
                <div class="col-12">
                    <div class="btn-group" role="toolbar" aria-label="Basic example">
                        <%= link_to gallery_path  do%>
                            <%= button_tag "Back to Gallery Home", type: 'button', class: 'btn btn-primary btn-small' %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-5">
        <div class="card card-body shadow-lg border-1 border-radius-xl col-12">
            <div class="row">
                <%= render 'form', gallery: @gallery %>
            </div>
            <%= link_to 'Cancel', gallery_path %>
        </div>
    </div>
</div>